name: model-wine-quality
on: [push]
permissions:
    id-token: write
    contents: write            
    security-events: write  
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - name: cml_run
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py

          echo "MODEL METRICS"
          cat metrics.txt

          echo "## Model metrics:" >> report.md
          cat metrics.txt >> report.md
          echo "## Data viz">>report.md
          echo "## Data viz" >> report.md
          echo '![](./feature_importance.png)' >> report.md
          echo '![](./residuals.png)' >> report.md
        
