name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1

      - name: Upgrade pip
        run: /usr/bin/python3 -m pip install --upgrade pip

      - name: Update Node.js to v16
        run: |
          curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
          apt-get install -y nodejs

      - name: cml_run
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py

          echo "## MODEL METRICS" > report.md
          cat metrics.txt >> report.md

          echo "## Data viz" >> report.md
          echo "![feature importance](feature_importance.png)" >> report.md
          echo "![residuals](residuals.png)" >> report.md

          cml-send-comment report.md
